[package]
name = "axum-helmet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
helmet-core = { path = "../helmet-core", version = "0.1.0" }
tower = "0.4"
tower-service = "0.3"
http = "1.0"
pin-project-lite = "0.2"
tokio = "1.35"

[dev-dependencies]
axum-test = "14.2"
tokio = { version = "1.35", features = ["rt-multi-thread"] }
