[package]
name = "axum-helmet"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Kovacs <kovacsemod@gmail.com>"]
description = "HTTP security headers middleware core for axum web framework"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/danielkov/rust-helmet"
repository = "https://github.com/danielkov/rust-helmet"
keywords = ["helmet", "security", "middleware", "rust", "axum"]
categories = ["web-programming", "http", "middleware"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0"
helmet-core = { path = "../helmet-core", version = "0" }
tower = "0"
tower-service = "0"
http = "1"
pin-project-lite = "0"
tokio = "1"

[dev-dependencies]
axum-test = "16"
tokio = { version = "1", features = ["rt-multi-thread"] }
